name: 打包应用并上传服务器

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
      - name: 安装node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: 安装依赖
        run: npm install

      - name: 打包
        run: npm run build

      - name: 发布到远程服务器
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "index.html"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/var/www/blog/"
