name: Build app
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 使用别人的action
            - uses: actions/checkout@master
            - name: 安装node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.17.0
            - name: npm install
              run: npm install
            - name: npm run build
              run: npm run build
            - name: Deploy
              uses: cross-the-world/scp-pipeline@master
              env:
                  WELCOME: 'ssh scp ssh pipelines'
                  LASTSSH: 'Doing something after copying'
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  user: ${{ secrets.REMOTE_USER }}
                  pass: ${{ secrets.USER_PASS }}
                  connect_timeout: 10s
                  local: './dist/*'
                  remote: ${{ REMOTE_TARGET }}
